title: Home
# tagline: 
# description: This workshop aims at bringing together the contributors and users of Enzyme in particular, and people interested in automatic differentiation within the LLVM infrastructure in general, for two days of fast-paced high-bandwidth idea exchange and collaboration bootstrapping.
logo: /img/logo.png
locale: en_US
lang: en
url: https://gymni.ch


exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll_version_plugin
  - jekyll_include_plugin
  - jekyll-octicons
